---
title: "Bistability"
author: "Daniel Kaschek"
date: "September 13, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dMod)
library(deSolve)
library(trust)
library(cowplot)
setwd("/tmp")

```

# Generate dynamic system

```{r}
# Add reactions		
reactions <- NULL
reactions <- addReaction(reactions, "TCA_buffer", "TCA_cell", 
			 rate = "import*TCA_buffer", 
			 description = "Uptake")
reactions <- addReaction(reactions, "TCA_cell", "TCA_buffer", 
			 rate = "export_sinus*TCA_cell",
			 description = "Sinusoidal export")
reactions <- addReaction(reactions, "TCA_cell", "TCA_cana", 
			 rate = "export_cana*TCA_cell", 
			 description = "Canalicular export")
reactions <- addReaction(reactions, "TCA_cana", "TCA_buffer", 
			 rate = "reflux*TCA_cana", 
			 description = "Reflux into the buffer")

# Translate into ODE model
mymodel <- odemodel(reactions, modelname = "bamodel")

# Generate prediction function from ODE model
x <- Xs(mymodel)

```

# Illustrate the prediction function

```{r}
times <- seq(0, 50, .1)
pars <- c(TCA_buffer = 1,
          TCA_cell = 0,
          TCA_cana = 0,
          import = 0.2,
          export_sinus = 0.2,
          export_cana = 0.04,
          reflux = 0.1)

out <- x(times, pars)
P1 <- plot(out) + theme(legend.position = "none") + facet_wrap(~name, scales = "free", ncol = 1)

out <- getDerivs(x(times, pars[4:7], fixed = pars[-(4:7)]))
P2 <- plot(out) + facet_wrap(~name, scales = "free", ncol = 3) + theme(legend.position = "none")

ggdraw() +
  draw_plot(P1, x = 0, width = 0.3) +
  draw_plot(P2, x = 0.3 , width = 0.7) +
  draw_plot_label(c("A", "B"), c(0, 0.3), c(1, 1), size = 12)

ggsave("~/Abteilung_Timmer/RProjects/publication_dMod/images/figure1.pdf", width = 8, height = 4.3, device = cairo_pdf, family = "latin modern roman")

```


# Illustrate observation function and simulation of data

```{r}

# Generate observation function
observables <- eqnvec(
  buffer = "s*TCA_buffer",
  cellular = "s*(TCA_cana + TCA_cell)"
)

g <- Y(observables, reactions,
       compile = TRUE, modelname = "obsfn")

# Reset parameter values
pars["TCA_cell"] <- 0.3846154
pars["TCA_cana"] <- 0.1538462
pars["TCA_buffer"] <- 0
pars["s"] <- 1e3

out <- (g*x)(times, pars, conditions = "standard")

# Simuate data
set.seed(1)
timesD <- c(0.1, 1, 3, 7, 11, 15, 20, 41)
datasheet <- subset(wide2long(out), 
                    time %in% timesD & name %in% names(observables))
datasheet$sigma <- sqrt(datasheet$value + 1)
datasheet$value <- rnorm(nrow(datasheet), datasheet$value, datasheet$sigma)

data <- as.datalist(datasheet)


plot(out, data) + facet_wrap(~name, nrow = 1, scales = "free") + theme(legend.position = "none")
ggsave("~/Abteilung_Timmer/RProjects/publication_dMod/images/figure2.pdf", width = 8, height = 2, device = cairo_pdf, family = "latin modern roman")



```


# Parameter transformations

```{r}

p <- P(
  trafo = eqnvec(
    TCA_buffer = "0",
    TCA_cell = "exp(TCA_cell)",
    TCA_cana = "exp(TCA_cana)",
    import = "exp(import)",
    export_sinus = "exp(export_sinus)",
    export_cana = "exp(export_cana)",
    reflux = "exp(reflux)",
    s = "exp(s)"
  ),
  condition = "standard"
)

outerpars <- getParameters(p)
pouter <- structure(rep(-1, length(outerpars)), names = outerpars)

plot((g*x*p)(times, pouter), data) + facet_wrap(~name, nrow = 1, scales = "free") + theme(legend.position = "none")
ggsave("~/Abteilung_Timmer/RProjects/publication_dMod/images/figure3.pdf", width = 8, height = 2, device = cairo_pdf, family = "latin modern roman")

obj <- normL2(data, g*x*p) + constraintL2(pouter, sigma = 10)
myfit <- trust(obj, pouter, rinit = 1, rmax = 10)

plot((g*x*p)(times, myfit$argument), data) + facet_wrap(~name, nrow = 1, scales = "free") + theme(legend.position = "none")
ggsave("~/Abteilung_Timmer/RProjects/publication_dMod/images/figure4.pdf", width = 8, height = 2, device = cairo_pdf, family = "latin modern roman")


```

```{r}

out_mstrust <- mstrust(obj, pouter, rinit = 1, rmax = 10, iterlim = 500,
                       sd = 4, 
                       cores = 4, fits = 50)

myframe <- as.parframe(out_mstrust)

plotValues(myframe, value < 100)
plotPars(myframe, value < 100)


P1 <- plotValues(myframe, value < 100) + scale_shape_manual(values = 1)

myframe$value <- as.factor(round(myframe$value, 2))
P2 <- plotPars(myframe, as.numeric(as.character(value)) < 100) + geom_point(color = "white") + geom_point(pch = 1) + scale_color_dMod()

ggdraw() +
  draw_plot(P1, x = 0, width = 0.5) +
  draw_plot(P2, x = 0.5 , width = 0.5) +
  draw_plot_label(c("A", "B"), c(0, 0.5), c(1, 1), size = 12)

ggsave("~/Abteilung_Timmer/RProjects/publication_dMod/images/figure5.pdf", width = 8, height = 3, device = cairo_pdf, family = "latin modern roman")


```



```{r}

pars["reflux"] <- 1e3
out <- (g*x)(times, pars, conditions = "open")

datasheet <- subset(wide2long(out), 
                    time %in% timesD & name %in% names(observables))
datasheet$sigma <- sqrt(datasheet$value + 1)
datasheet$value <- rnorm(nrow(datasheet), datasheet$value, datasheet$sigma)

data <- data + as.datalist(datasheet)
plot(data)

```

```{r}

trafo <- summary(p)$standard$equations
trafo["reflux"] <- "exp(reflux_open)"
p <- p + P(trafo, condition = "open")

outerpars <- getParameters(p)
pouter <- structure(rep(-1, length(outerpars)), names = outerpars)

obj <- normL2(data, g*x*p) + constraintL2(pouter, sigma = 10)



out_mstrust <- mstrust(obj, pouter, rinit = 1, rmax = 10, sd = 4, cores = 4, fits = 50, iterlim = 500)
myframe <- as.parframe(out_mstrust)
plotValues(myframe, value < 100)
plotPars(myframe, value < 100)

bestfit <- as.parvec(myframe)
P0 <- plot((g*x*p)(times, bestfit), data) + facet_wrap(~name, scales = "free", nrow = 1)

P1 <- plotValues(myframe, value < 100) + scale_shape_manual(values = 1)

myframe$value <- as.factor(round(myframe$value, 2))
P2 <- plotPars(myframe, as.numeric(as.character(value)) < 100) + geom_point(color = "white") + geom_point(pch = 1) + scale_color_dMod()

ggdraw() +
  draw_plot(P0, x = 0, width = 1, y = .6, height = .4) +
  draw_plot(P1, x = 0, width = 0.5, y = 0, height = .6) +
  draw_plot(P2, x = 0.5 , width = 0.5, y = 0, height = .6) +
  draw_plot_label(c("A", "B", "C"), c(0, 0, 0.5), c(1, .6, .6), size = 12)


ggsave("~/Abteilung_Timmer/RProjects/publication_dMod/images/figure6.pdf", width = 8, height = 4, device = cairo_pdf, family = "latin modern roman")

```



```{r}

profiles <- profile(obj, bestfit, names(bestfit), limits = c(-5, 5), cores = 4)


P1 <- plotProfile(profiles) + facet_wrap(~name, nrow = 2, scales = "free_x") + theme(legend.position = "top", legend.box = "horizontal")



P2 <- plotPaths(profiles, whichPar = "s") + facet_wrap(~combination, nrow = 1, scales = "free_x") + theme(legend.position = "none")

ggdraw() +
  draw_plot(P1, x = 0, width = 1, y = 0.3, height = .7) +
  draw_plot(P2, x = 0 , width = 1, y = 0, height = .3) +
  draw_plot_label(c("A", "B"), c(0, 0), c(1, .3), size = 12)

ggsave("~/Abteilung_Timmer/RProjects/publication_dMod/images/figure7.pdf", width = 8, height = 6, device = cairo_pdf, family = "latin modern roman")

```




```{r}

pSS <- NULL
trafos <- summary(p)
conditions <- names(trafos)
for (n in conditions) {
  
  equations <- trafos[[n]]$equations
  equations["TCA_cana"] <- "exp(export_cana)*exp(TCA_cell)/exp(reflux)"
  pSS <- pSS + P(equations, condition = n)
  
}

outerpars <- getParameters(pSS)
pouter <- structure(rep(-1, length(outerpars)), names = outerpars)

obj <- normL2(data, g*x*pSS) + constraintL2(pouter, sigma = 10)


out_mstrust <- mstrust(obj, pouter, rinit = 1, rmax = 10, sd = 4, cores = 4, fits = 50, iterlim = 500)
myframe <- as.parframe(out_mstrust)
bestfit <- as.parvec(myframe)




```



```{r}
# Add reactions		
reactions <- NULL
reactions <- addReaction(reactions, "TCA_buffer", "TCA_cell", 
			 rate = "import*TCA_buffer", 
			 description = "Uptake")
reactions <- addReaction(reactions, "TCA_cell", "TCA_buffer", 
			 rate = "export_sinus*TCA_cell",
			 description = "Sinusoidal export")
reactions <- addReaction(reactions, "TCA_cell", "TCA_cana", 
			 rate = "export_cana*TCA_cell", 
			 description = "Canalicular export")
reactions <- addReaction(reactions, "TCA_cana", "TCA_buffer", 
			 rate = "(reflux*(1-switch) + reflux_open*switch)*TCA_cana", 
			 description = "Reflux into the buffer")
reactions <- addReaction(reactions, "0", "switch", 
       rate = "0", 
       description = "Create a switch")

# Translate into ODE model
mymodel <- odemodel(reactions, modelname = "bamodel")

# Set up implicit parameter transformation
f <- as.eqnvec(reactions)[c("TCA_buffer", "TCA_cana", "TCA_cell")]
f["TCA_cell"] <- "TCA_buffer + TCA_cana + TCA_cell - TCA_tot"
pSS <- P(f, "TCA_tot", method = "implicit", 
         compile = TRUE, modelname = "pfn")

# Set up explicit parameter transformation
innerpars <- unique(c(getParameters(mymodel), 
                      getSymbols(observables), 
                      getSymbols(f)))
trafo <- as.eqnvec(innerpars, names = innerpars)
trafo[reactions$states] <- "0"
trafo <- replaceSymbols(innerpars, 
                        paste0("exp(", innerpars, ")"), 
                        trafo)
p <- P(trafo)


# Set up prediction function with events
event.buffer <- data.frame(var = "TCA_buffer", time = 0, value = 0, method = "replace")
event.open <- data.frame(var = "switch", time = 0, value = 1, method = "replace")

x <- Xs(mymodel, events = event.buffer, condition = "standard") + 
     Xs(mymodel, events = rbind(event.buffer, event.open), condition = "open")

# Generate observation function with modified states/parameters
g <- Y(observables, 
       states = reactions$states, 
       parameters = setdiff(innerpars, reactions$states),
       compile = TRUE, modelname = "obsfn")

# Generate objective function
outerpars <- getParameters(p)
pouter <- structure(rep(-1, length(outerpars)), names = outerpars)
obj <- normL2(data, g*x*pSS*p) + constraintL2(pouter, sigma = 10)


out_mstrust <- mstrust(obj, pouter, rinit = 1, rmax = 10, sd = 4, cores = 4, fits = 50, iterlim = 500)
myframe <- as.parframe(out_mstrust)
plotValues(myframe)
bestfit <- as.parvec(myframe)


plot((g*x*pSS*p)(times, bestfit), data)
  
```



```{r}


profiles_SS <- profile(obj, bestfit, names(bestfit), limits = c(-5, 5), cores = 4)

profdata <- attr(plotProfile(list(noSS = profiles, SS_explicit = profiles_SS_analytic, SS_implicit = profiles_SS), mode == "data") , "data")
profdata.zero <- subset(profdata, is.zero)

ggplot(profdata, aes(x=par, y=delta, group=interaction(proflist), color=proflist, pch = proflist)) + facet_wrap(~name, scales="free_x", nrow = 2) + 
  geom_hline(yintercept=c(1, 2.7, 3.84), lty=2, color="gray") + 
  geom_line(alpha = .5) +
  geom_point(data = profdata.zero, pch = 19, alpha = .5) +
  geom_point(alpha = 1, data = profdata[seq(1, nrow(profdata), by = 10),]) + #geom_point(aes=aes(size=1), alpha=1/3) +
  scale_shape_manual(values = c(NA, 3, 4)) +
  #scale_linetype_manual(values = c(1, 3, 4)) +
  ylab(expression(paste("CL /", Delta*chi^2))) +
  scale_y_continuous(breaks=c(1, 2.7, 3.84), labels = c("68% / 1   ", "90% / 2.71", "95% / 3.84"), limits = c(NA, 5)) +
  xlab("parameter value") + scale_color_dMod() + 
  theme_dMod()+ theme(legend.position = c(0.9, 0.2), legend.box = "vertical")
  

ggsave("~/Abteilung_Timmer/RProjects/publication_dMod/images/figure8.pdf", width = 8, height = 4, device = cairo_pdf, family = "latin modern roman")

```



```{r}

library(scales)

obj.validation <- datapointL2(name = "TCA_cell", time = 41, value = "d1", sigma = .002, condition = "standard")
myfit <- trust(obj + obj.validation, c(d1 = 1, bestfit[-7]), fixed = c(TCA_tot = log(1)), rinit = 1, rmax = 10)

plot((g*x*pSS*p)(times, myfit$argument, fixed = c(TCA_tot = log(1))), data)

profile_prediction <- profile(obj + obj.validation, myfit$argument, "d1", limits = c(-5, 5), fixed = c(TCA_tot = log(1)))

P1 <- plotProfile(list("t = 41" = profile_prediction)) + theme(legend.position = "top", legend.direction = "vertical", legend.box.just = "left") + scale_x_continuous(breaks = pretty_breaks(n = 3))

times.vali <- c(1, 3, 7, 11, 15, 20, 41)
cbdata <- NULL
for (t in times.vali) {
  obj.validation <- datapointL2(name = "TCA_cell", time = t, value = "d1", sigma = .002, condition = "standard")
  myfit <- trust(obj + obj.validation, c(d1 = 1, bestfit[-7]), fixed = c(TCA_tot = log(1)), rinit = 1, rmax = 10)
  profile_prediction <- profile(obj + obj.validation, myfit$argument, "d1", limits = c(-5, 5), fixed = c(TCA_tot = log(1)))
  outerpoints <- profile_prediction[c(1, nrow(profile_prediction)), "d1"]
  cbdata <- rbind(cbdata, 
                  data.frame(name = "TCA_cell", time = t, value = NaN, sigma = NaN, lower = outerpoints$d1[1], upper = outerpoints$d1[2], condition = "standard"))
  
}


myfit <- trust(obj, c(NULL, bestfit[-7]), fixed = c(TCA_tot = log(1)), rinit = 1, rmax = 10)
P2 <- plot((g*x*pSS*p)(seq(sqrt(0.1), sqrt(50), len = 200)^2, myfit$argument), data) + 
  geom_ribbon(aes(x = time, ymin = upper, ymax = lower), data = cbdata, alpha = .4, lty = 2) +
  geom_point(aes(x = time, y = upper, color = condition), data = cbdata, pch = 4) + 
  geom_point(aes(x = time, y = lower, color = condition), data = cbdata, pch = 4) +
   scale_x_log10() + xlab("time (logarithmically)") +
  scale_fill_dMod() + theme(legend.position = c(.88, .2), legend.background = element_rect(colour = "black"))

ggdraw() +
  draw_plot(P1, x = 0, width = .3) +
  draw_plot(P2, x = 0.3 , width = .7) +
  draw_plot_label(c("A", "B"), c(0, .3), c(1, 1), size = 12)

ggsave("~/Abteilung_Timmer/RProjects/publication_dMod/images/figure9.pdf", width = 8, height = 4, device = cairo_pdf, family = "latin modern roman")



```




















# Knock-out of sinusoidal export

```{r}

pars["TCA_buffer"] <- 1
pars["TCA_cell"] <- 0
pars["TCA_cana"] <- 0
pars["reflux"] <- 0.1
pars["export_sinus"] <- 0

out <- x(timesI, pars, conditions = "sinus_inhibitor")
pars[c("TCA_cell", "TCA_cana")] <- tail(out$sinus_inhibitor, 1)[1, 3:4]
pars["TCA_buffer"] <- 0

out <- (g*x)(times, pars, conditions = "sinus_inhibitor")

datasheet <- subset(wide2long(out), time %in% timesD & name %in% names(observables))
datasheet$sigma <- sqrt(datasheet$value + 1)
datasheet$value <- rnorm(nrow(datasheet), datasheet$value, datasheet$sigma)
datasheet$condition <- "sinus_inhibitor"

data <- data + as.datalist(datasheet)
plot(data)

```

```{r}


trafo <- summary(pSS)$standard$equations
trafo <- replaceSymbols(c("export_sinus", "TCA_cell"),
                        c("export_sinus_inhibited", "TCA_cell_inhibited"),
                        trafo)

pSS <- pSS + P(trafo, condition = "sinus_inhibitor")

outerpars <- getParameters(pSS)
pouter <- structure(rep(-1, length(outerpars)), names = outerpars)


obj <- normL2(data, g*x*pSS) + constraintL2(pouter, sigma = 10) + constraintL2(c(s = log(1e3)), sigma = .1, attr.name = "data")


out_mstrust <- mstrust(obj, pouter, rinit = 1, rmax = 10, sd = 4, cores = 4, fits = 50, iterlim = 500)
myframe <- as.parframe(out_mstrust)
bestfit <- as.parvec(myframe)

```





```{r}


profiles_approx_sinus <- profile(obj, bestfit, names(bestfit), limits = c(-5, 5), cores = 4)


plotProfile(list(noSS = profiles, SS = profiles_SS, inhibitor = profiles_approx_sinus), mode == "data")

```














```{r}
trafos <- summary(p)
pSS <- NULL
for (n in names(trafos)) {
  equations <- trafos[[n]][["equations"]]
  equations["TCA_cana"] <- "exp(export_cana)*exp(TCA_cell)/exp(reflux)"
  pSS <- pSS + P(equations, condition = n)
}


outerpars <- getParameters(pSS)
pouter <- structure(rep(-1, length(outerpars)), names = outerpars)

obj <- normL2(data, g*x*pSS) + constraintL2(pouter, sigma = 10)
out_mstrust <- mstrust(obj, pouter, rinit = 1, rmax = 10, sd = 4, cores = 4, fits = 50, iterlim = 500)
myframe <- as.parframe(out_mstrust)
plotValues(myframe[1:39,])
bestfit <- as.parvec(myframe)





plot((g*x*pSS)(times, bestfit), data)

```



# Use steady state constraints

```{r}

p <- P(
  trafo = resolveRecurrence(eqnvec(
    TCA_buffer = "0",
    TCA_cell = "exp(TCA_cell)",
    import = "exp(import)",
    export_sinus = "exp(export_sinus)",
    export_cana = "exp(export_cana)",
    reflux = "exp(reflux)",
    s = "10000",
    TCA_cana = "export_cana*TCA_cell/reflux"
  )),
  condition = "standard"
)

outerpars <- getParameters(p)
pouter <- structure(rep(-1, length(outerpars)), names = outerpars)

obj <- normL2(data, g*x*p) + constraintL2(pouter, sigma = 10)



plot((g*x*p)(times, myfit$argument), data)


```












# Use numeric steady states
```{r}

ssconstr <- as.eqnvec(reactions)
ssconstr["TCA_buffer"] <- "TCA_buffer + TCA_cana + TCA_cell - TCA_tot"
pSS <- P(ssconstr, parameters = "TCA_tot", compile = TRUE, modelname = "pSS", method = "implicit")


p <- P(
  trafo = eqnvec(
    TCA_buffer = "1",
    TCA_cana = "1",
    TCA_cell = "1",
    TCA_tot = "exp(TCA_tot)",
    import = "exp(import)",
    export_sinus = "exp(export_sinus)",
    export_cana = "exp(export_cana)",
    reflux = "exp(reflux)",
    s = "exp(s)"
  ),
  condition = "standard"
)


outerpars <- getParameters(p)
pouter <- structure(rep(-1, length(outerpars)), names = outerpars)

myevent <- data.frame(
  var = "TCA_buffer",
  time = 0,
  value = 0,
  method = "replace"
)

x <- Xs(mymodel, events = myevent)

obj <- normL2(data, g*x*pSS*p) + constraintL2(pouter, sigma = 10) + constraintL2(c(TCA_tot = log(1)), sigma = .01, attr.name = "data")
myfit <- trust(obj, pouter, rinit = 1, rmax = 10)


plot((g*x*pSS*p)(times, myfit$argument), data)


```


```{r}

profiles <- profile(obj, myfit$argument, names(myfit$argument), limits = c(-5, 5), method = "optimize", cores = 4)

profiles_approx <- profile(obj, myfit$argument, names(myfit$argument), limits = c(-5, 5), algoControl = list(gamma = 0), cores = 4)

plotProfile(list(profiles, profiles_approx), mode == "data")

```
